#!/usr/bin/env python3
"""Generate the catalog caps reference from the validator constants.

`code-comments` and `documentation-layout` are meant to be the single source
of truth for their numeric caps, but docs and skills kept restating those
numbers by hand and the copies drifted. This generator reads
the constants straight off the two validator modules and renders a tiny,
committed Markdown reference. Docs and skills point at that render instead of
restating a number, so the caps can never drift between code and prose.

Mirrors the seed-skills pattern: `generate-caps-reference` writes the render
and `check-caps-reference-drift` fails commit when it goes stale. Like the
generated operator-command dumps, the render is the
off-disk, greppable answer so a cold agent reads the real cap without running
the validator.

The render is deterministic and timestamp-free, so the drift check is pure.
"""
from __future__ import annotations

import difflib
import sys
from pathlib import Path

from agentic_os.pre_commit import check_code_comments as cc
from agentic_os.pre_commit import check_documentation_layout as dl

TRACKER = "docs/catalog-caps-reference.md"

_REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = _REPO_ROOT / "docs" / "catalog-caps-reference.md"

# Source-of-truth pointers, rendered so the reference says where each number
# lives. Validator path is repo-relative for the "read the constant" pointer.
CODE_COMMENTS_SRC = "agentic_os/pre_commit/check_code_comments.py"
DOC_LAYOUT_SRC = "agentic_os/pre_commit/check_documentation_layout.py"

GENERATED_HEADER = (
    "<!-- GENERATED by generate-caps-reference - do not hand-edit. -->\n"
    "<!-- Regenerate: just gen-caps-reference (check-caps-reference-drift "
    "guards staleness). -->\n"
)


def _caps() -> list[tuple[str, str, str, str]]:
    """The cap rows: (hook, name, value, note). Pulled live from constants."""
    return [
        (
            "code-comments",
            "comment line chars",
            str(cc.MAX_COMMENT_LINE_CHARS),
            "max characters on a standalone comment line",
        ),
        (
            "code-comments",
            "contiguous comment lines",
            str(cc.MAX_CONTIGUOUS_COMMENT_LINES),
            "max consecutive comment lines. A top-of-file header block is "
            "exempt unless `header_cap` is set",
        ),
        (
            "documentation-layout",
            "markdown lines (micro band)",
            str(dl.BAND_CAPS["micro"][0]),
            'lines, blank ones included, where `band = "micro"` is declared',
        ),
        (
            "documentation-layout",
            "markdown chars (micro band)",
            str(dl.BAND_CAPS["micro"][1]),
            'characters where `band = "micro"` is declared',
        ),
        (
            "documentation-layout",
            "docs count (micro band)",
            str(dl.BAND_CAPS["micro"][2]),
            '`docs/*.md` files where `band = "micro"` is declared, the cap that '
            'separates micro from small',
        ),
        (
            "documentation-layout",
            "markdown lines (small band)",
            str(dl.BAND_CAPS["small"][0]),
            'lines, blank ones included, where `band = "small"` is declared',
        ),
        (
            "documentation-layout",
            "markdown chars (small band)",
            str(dl.BAND_CAPS["small"][1]),
            'characters where `band = "small"` is declared',
        ),
        (
            "documentation-layout",
            "docs count (small band)",
            str(dl.BAND_CAPS["small"][2]),
            '`docs/*.md` files where `band = "small"` is declared',
        ),
        (
            "documentation-layout",
            "markdown lines (large band)",
            str(dl.BAND_CAPS["large"][0]),
            'lines, blank ones included, where `band = "large"` is declared',
        ),
        (
            "documentation-layout",
            "markdown chars (large band)",
            str(dl.BAND_CAPS["large"][1]),
            'characters where `band = "large"` is declared',
        ),
        (
            "documentation-layout",
            "docs count (large band)",
            str(dl.BAND_CAPS["large"][2]),
            '`docs/*.md` files where `band = "large"` is declared',
        ),
        (
            "documentation-layout",
            "guide lines (small band)",
            str(dl.BAND_CAPS["small"][0] * dl.GUIDE_SIZE_FACTOR),
            "lines for a `guides/*.md` narrative walkthrough, "
            f"{dl.GUIDE_SIZE_FACTOR}x the small band's per-doc cap",
        ),
        (
            "documentation-layout",
            "guide chars (small band)",
            str(dl.BAND_CAPS["small"][1] * dl.GUIDE_SIZE_FACTOR),
            "characters for a `guides/*.md` page where "
            '`band = "small"` is declared',
        ),
        (
            "documentation-layout",
            "guide lines (large band)",
            str(dl.BAND_CAPS["large"][0] * dl.GUIDE_SIZE_FACTOR),
            "lines for a `guides/*.md` narrative walkthrough, "
            f"{dl.GUIDE_SIZE_FACTOR}x the large band's per-doc cap",
        ),
        (
            "documentation-layout",
            "guide chars (large band)",
            str(dl.BAND_CAPS["large"][1] * dl.GUIDE_SIZE_FACTOR),
            "characters for a `guides/*.md` page where "
            '`band = "large"` is declared',
        ),
        (
            "documentation-layout",
            "README overview lines",
            str(dl.TRIFECTA_MAX_LINES),
            "lines, blank ones included, for the root README.md",
        ),
        (
            "documentation-layout",
            "README overview chars",
            str(dl.TRIFECTA_MAX_CHARS),
            "characters for the root README.md",
        ),
        (
            "documentation-layout",
            "AGENTS.md lines (default)",
            str(dl.AGENTS_DEFAULT_MAX_LINES),
            "AGENTS.md shared default "
            "(override per-repo with `agents_md_max_lines`)",
        ),
        (
            "documentation-layout",
            "AGENTS.md chars (default)",
            str(dl.AGENTS_DEFAULT_MAX_CHARS),
            "AGENTS.md shared default "
            "(override per-repo with `agents_md_max_chars`)",
        ),
        (
            "documentation-layout",
            "README.md lines (default)",
            str(dl.README_DEFAULT_MAX_LINES),
            "the root README.md defaults to the trifecta line cap "
            "(override per-repo with `readme_max_lines`)",
        ),
        (
            "documentation-layout",
            "README.md chars (default)",
            str(dl.README_DEFAULT_MAX_CHARS),
            "the root README.md defaults to the trifecta char cap "
            "(override per-repo with `readme_max_chars`)",
        ),
        (
            "documentation-layout",
            "module README lines",
            str(dl.README_MAX_LINES),
            "non-blank lines for a co-located module README "
            "(outpost or homestead shape)",
        ),
        (
            "documentation-layout",
            "module README prose chars",
            str(dl.README_MAX_PROSE_CHARS),
            "characters per prose line in a module README "
            "(the pointer line is exempt)",
        ),
    ]


def render_doc() -> str:
    """Deterministic Markdown render of the caps. No timestamps."""
    lines: list[str] = [GENERATED_HEADER.rstrip("\n")]
    lines.append("")
    lines.append("# Catalog validator caps - generated reference")
    lines.append("")
    lines.append(
        "Single source of truth for the numeric caps the `code-comments` and "
        "`documentation-layout` validators enforce. Generated from the "
        "validator constants, so the caps can never drift between code and "
        "prose. Point here by reference rather than restating a number. To "
        "change a cap, edit the constant in the validator and run "
        "`just gen-caps-reference`, never this file."
    )
    lines.append("")
    lines.append(
        f"Constants live in [`{CODE_COMMENTS_SRC}`]({_rel_link(CODE_COMMENTS_SRC)}) "
        f"and [`{DOC_LAYOUT_SRC}`]({_rel_link(DOC_LAYOUT_SRC)})."
    )
    lines.append("")
    last_hook = None
    for hook, name, value, note in _caps():
        if hook != last_hook:
            if last_hook is not None:
                lines.append("")
            lines.append(f"## {hook}")
            lines.append("")
            last_hook = hook
        lines.append(f"* **{name}** - {value} - {note}.")
    return "\n".join(lines) + "\n"


def _rel_link(src: str) -> str:
    """Relative link from docs/ to a repo-root path."""
    return f"../{src}"


def generate(doc_path: Path = DOC_PATH) -> int:
    doc_path.write_text(render_doc(), encoding="utf-8")
    print(f"generate-caps-reference: wrote {doc_path.name} ({len(_caps())} caps)")
    return 0


def check_drift(doc_path: Path = DOC_PATH) -> int:
    """Byte-compare the doc against a fresh render.

    That covers every number and every word, so the doc cannot drift from
    this generator. It cannot cover this generator's own prose drifting
    from what the validator measures, which is how the band rows came to
    say "non-blank" (#1331, #1337). A behavior test guards that instead:
    tests/test_check_documentation_layout.py asserts blank lines count.
    """
    expected = render_doc()
    actual = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""
    if actual == expected:
        print(f"caps-reference-drift: {doc_path.name} in sync")
        return 0
    sys.stderr.write(
        f"caps-reference-drift: {doc_path.name} is missing, stale, or "
        "hand-edited. Run `just gen-caps-reference` to regenerate.\n"
    )
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=f"{doc_path.name} (on disk)",
        tofile="expected (fresh generate)",
        lineterm="",
    )
    for line in list(diff)[:40]:
        sys.stderr.write(line + "\n")
    return 1


def main() -> int:
    """Console entry for generate-caps-reference. `--check` reports drift."""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify docs/catalog-caps-reference.md is in sync; exit 1 on drift",
    )
    args = parser.parse_args()
    return check_drift() if args.check else generate()


def check_drift_main() -> int:
    """Console entry for the check-caps-reference-drift pre-commit hook."""
    return check_drift()


if __name__ == "__main__":
    sys.exit(main())
