package main

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/urfave/cli/v3"
)

const (
	bundlesCommand         = "bundles"
	bundlesFormat          = "aterm.bundles.v1"
	bundleIdentifierPrefix = "me.coilysiren.aterm"
	bundleNameSeparator    = " :: "
	bundleTerminalName     = "kitty"
	bundleIconName         = "aterm"
	bundleMarker           = "# generated by `aterm bundles`"
	bundleDirMode          = 0o755
	bundleFileMode         = 0o644
	bundleExecMode         = 0o755
	// The shell verb that opens the same sessions, so the word already means
	// "the role apps" before anyone types it into Spotlight.
	defaultBundleTag = "acompose"
)

// Committed like aterm/sounds, so a bundle write needs no renderer on the host.

//go:embed icons/*.icns
var roleIcons embed.FS

// roleIcon is the committed art for a role, or nil when the role has none. A
// role without art keeps the system icon rather than a broken reference.
func roleIcon(role string) []byte {
	raw, err := roleIcons.ReadFile("icons/" + role + ".icns")
	if err != nil {
		return nil
	}
	return raw
}

type bundleSpec struct {
	Role             string
	DisplayName      string
	Person           string
	Version          string
	BakedPath        string
	Icon             bool
	WorkingDirectory string
	ATermBin         string
	AOSBin           string
	AgentComposeBin  string
	TerminalBin      string
}

// name is the on-disk basename. macOS renders a POSIX colon as a slash, so
// the house ` // ` separator has to be stored as ` :: `. See docs/aterm.md.
func (s bundleSpec) name() string {
	parts := []string{strings.TrimSpace(s.Person), strings.TrimSpace(s.DisplayName)}
	kept := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "" {
			kept = append(kept, strings.ReplaceAll(part, "/", "-"))
		}
	}
	return strings.Join(kept, bundleNameSeparator)
}

// displayName is the same name as the Dock draws it, for prose and alerts.
func (s bundleSpec) displayName() string {
	return strings.ReplaceAll(s.name(), bundleNameSeparator, " // ")
}

// executable stays a plain slug. Only the bundle directory carries the
// display name, and nothing renders what is inside Contents/MacOS.
func (s bundleSpec) executable() string { return "aterm-" + s.Role }

func (s bundleSpec) identifier() string { return bundleIdentifierPrefix + "." + s.Role }

type bundleItem struct {
	Role       string `json:"role"`
	Person     string `json:"person"`
	Seat       string `json:"seat"`
	Name       string `json:"name"`
	Identifier string `json:"identifier"`
	Path       string `json:"path"`
	Executable string `json:"executable"`
	Terminal   string `json:"terminal"`
	Launcher   string `json:"launcher"`
	Plist      string `json:"plist"`
}

type bundlePlan struct {
	Format        string       `json:"format"`
	Output        string       `json:"output"`
	Icon          string       `json:"icon"`
	Tag           string       `json:"tag"`
	Launcher      string       `json:"launcher"`
	LauncherBuild string       `json:"launcher_build"`
	Build         string       `json:"build"`
	Items         []bundleItem `json:"items"`
	Stale         []string     `json:"stale"`
}

func newBundlesCommand(deps commandDeps) *cli.Command {
	return &cli.Command{
		Name:  bundlesCommand,
		Usage: "write one macOS .app launcher per live role",
		Description: "Every live role becomes a launchable, Spotlight-searchable app that opens\n" +
			"the same window `aterm <role>` opens. The wrapper bakes in the binaries it\n" +
			"resolved, because a Finder launch carries none of your shell's PATH.",
		Flags: append(bundleBinaryFlags(), []cli.Flag{
			&cli.StringFlag{
				Name:  "output-dir",
				Value: defaultBundleDir(),
				Usage: "directory to write the bundles into",
			},
			&cli.StringFlag{
				Name:  "icon",
				Usage: "shared .icns for every bundle (macOS draws its generic app icon without one)",
			},
			&cli.StringFlag{
				Name:  "working-directory",
				Value: defaultWorkingDirectory(),
				Usage: "agent working directory baked into every bundle",
			},
			&cli.BoolFlag{
				Name:  "dry-run",
				Usage: "show what would be written, and write nothing",
			},
			&cli.BoolFlag{
				Name:  "json",
				Usage: "with --dry-run, the machine plan instead of the rendered one",
			},
		}...),
		Action: func(ctx context.Context, cmd *cli.Command) error {
			return runBundles(ctx, deps, cmd)
		},
	}
}

// bundleBinaryFlags rebuilds the root's binary flags rather than sharing them,
// so `aterm bundles --aos-bin ...` parses without depending on flag persistence.
func bundleBinaryFlags() []cli.Flag {
	return []cli.Flag{
		&cli.StringFlag{
			Name:  "tag",
			Value: defaultBundleTag,
			Usage: "Finder tag on every bundle, so one Spotlight word finds the set; empty writes none",
		},
		&cli.StringFlag{
			Name:    "aterm-bin",
			Value:   defaultATermBin,
			Usage:   "installed aterm the bundles call, resolved and baked in",
			Sources: cli.EnvVars("ATERM_BIN"),
		},
		&cli.StringFlag{
			Name:    "agent-compose-bin",
			Value:   defaultOverlayBin,
			Sources: cli.EnvVars("AGENT_COMPOSE_BIN"),
		},
		&cli.StringFlag{
			Name:    "aos-bin",
			Value:   defaultAOSBin,
			Sources: cli.EnvVars("AOS_BIN"),
		},
		&cli.StringFlag{
			Name:    "terminal-bin",
			Value:   defaultTerminalBin,
			Usage:   "terminal the bundles open",
			Sources: cli.EnvVars("ATERM_TERMINAL_BIN", "KITTY_BIN"),
		},
	}
}

func defaultBundleDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return filepath.Join(home, "Applications")
}

func runBundles(ctx context.Context, deps commandDeps, cmd *cli.Command) error {
	if runtime.GOOS != "darwin" {
		return withExit(exitUsage, fmt.Errorf(
			"bundles writes macOS .app launchers, and this host is %s", runtime.GOOS))
	}
	plan, err := buildBundlePlan(ctx, deps, cmd)
	if err != nil {
		return err
	}
	stdout := cmd.Root().Writer
	if cmd.Bool("json") && !cmd.Bool("dry-run") {
		return withExit(exitUsage, fmt.Errorf("--json applies to --dry-run"))
	}
	if cmd.Bool("dry-run") {
		if cmd.Bool("json") {
			encoded, err := json.MarshalIndent(plan, "", "  ")
			if err != nil {
				return fmt.Errorf("marshal the bundle plan: %w", err)
			}
			_, err = fmt.Fprintf(stdout, "%s\n", encoded)
			return err
		}
		return renderBundlePlan(stdout, plan)
	}
	if err := os.MkdirAll(plan.Output, bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", plan.Output, err)
	}
	// Every target is cleared before any is written, so a refusal partway down
	// the roster cannot leave half a Dock folder regenerated.
	for _, item := range plan.Items {
		if err := replaceable(item.Path); err != nil {
			return err
		}
	}
	for _, item := range plan.Items {
		if err := writeBundle(item, plan.Icon, plan.Tag); err != nil {
			return err
		}
	}
	return announceBundles(stdout, plan)
}

func buildBundlePlan(ctx context.Context, deps commandDeps, cmd *cli.Command) (bundlePlan, error) {
	agentCompose, err := requireBinary(deps.lookPath, cmd.String("agent-compose-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("agent-compose binary: %w", err)
	}
	roster, err := loadRoster(ctx, deps, agentCompose)
	if err != nil {
		return bundlePlan{}, err
	}
	aos, err := requireBinary(deps.lookPath, cmd.String("aos-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("aos binary: %w", err)
	}
	terminal, err := requireBinary(deps.lookPath, cmd.String("terminal-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("terminal binary: %w", err)
	}
	terminalTarget, err := resolveTerminalTarget(terminal)
	if err != nil {
		return bundlePlan{}, err
	}
	launcher, err := requireBinary(deps.lookPath, cmd.String("aterm-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("aterm binary: %w", err)
	}
	cwd, err := validateWorkingDirectory(cmd.String("working-directory"))
	if err != nil {
		return bundlePlan{}, err
	}
	output, err := filepath.Abs(strings.TrimSpace(cmd.String("output-dir")))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("resolve the output directory: %w", err)
	}
	icon, err := resolveIcon(cmd.String("icon"))
	if err != nil {
		return bundlePlan{}, err
	}
	bakedPath := livePathEntries(os.Getenv("PATH"))
	plan := bundlePlan{
		Format:        bundlesFormat,
		Output:        output,
		Icon:          icon,
		Tag:           strings.TrimSpace(cmd.String("tag")),
		Launcher:      launcher,
		LauncherBuild: launcherBuild(ctx, deps, launcher),
		Build:         version,
	}
	for _, role := range roster.Items {
		if len(role.nativeSeats()) == 0 {
			continue
		}
		seat := defaultSeat(ctx, deps, cmd.String("aos-bin"), role)
		spec := bundleSpec{
			Role:             role.Slug,
			DisplayName:      role.DisplayName,
			Person:           role.Identity.Name,
			Version:          version,
			BakedPath:        bakedPath,
			Icon:             icon != "" || roleIcon(role.Slug) != nil,
			WorkingDirectory: cwd,
			ATermBin:         launcher,
			AOSBin:           aos,
			AgentComposeBin:  agentCompose,
			// The resolved target, not the caller's path: a window launched
			// from a bundle passes its own, baking a cross-bundle dependency.
			TerminalBin: terminalTarget,
		}
		plan.Items = append(plan.Items, bundleItem{
			Role:       spec.Role,
			Person:     spec.Person,
			Seat:       seat,
			Name:       spec.displayName(),
			Identifier: spec.identifier(),
			Path:       filepath.Join(output, spec.name()+".app"),
			Executable: spec.executable(),
			Terminal:   terminalTarget,
			Launcher:   bundleLauncher(spec),
			Plist:      bundleInfoPlist(spec),
		})
	}
	if len(plan.Items) == 0 {
		return bundlePlan{}, withExit(exitOffRoster,
			fmt.Errorf("no live role has a launchable native seat"))
	}
	keep := make(map[string]bool, len(plan.Items))
	for _, item := range plan.Items {
		keep[item.Path] = true
	}
	plan.Stale = staleBundles(output, keep)
	return plan, nil
}

// launcherBuild asks the aterm the bundles will call for its own version. A
// bundle is only as new as that binary, not as the one generating. See docs.
func launcherBuild(ctx context.Context, deps commandDeps, launcher string) string {
	raw, err := deps.output(ctx, launcher, "--version")
	if err != nil {
		return ""
	}
	fields := strings.Fields(strings.TrimSpace(string(raw)))
	if len(fields) == 0 {
		return ""
	}
	return fields[len(fields)-1]
}

// staleLauncher is the split that made half of a fix look like a whole one:
// names and PATH come from this build, every window option from that one.
func (p bundlePlan) staleLauncher() bool {
	return p.LauncherBuild != "" && p.Build != "" && p.LauncherBuild != p.Build
}

// livePathEntries is the fallback for a login shell exporting no PATH, minus
// entries that do not resolve. See docs/aterm.md.
func livePathEntries(value string) string {
	kept := make([]string, 0)
	seen := make(map[string]bool)
	for _, entry := range filepath.SplitList(value) {
		entry = strings.TrimSpace(entry)
		if entry == "" || isShadowEntry(entry) {
			continue
		}
		// Rewrite before the dedup, so two Cellar versions of one formula
		// collapse to the single opt path they both stand for.
		entry = stableBrewEntry(entry)
		if seen[entry] {
			continue
		}
		if info, err := os.Stat(entry); err != nil || !info.IsDir() {
			continue
		}
		seen[entry] = true
		kept = append(kept, entry)
	}
	return strings.Join(kept, string(filepath.ListSeparator))
}

// A per-session shadow is reaped, so an entry under one dies with the session
// that wrote the bundle. The marker catches another seat's shadow too.
const nativeShadowMarker = "/aos/native/"

func isShadowEntry(entry string) bool {
	slashed := filepath.ToSlash(entry)
	if strings.Contains(slashed, nativeShadowMarker) {
		return true
	}
	for _, key := range []string{nativeSessionRootEnv, nativeSessionProjectsEnv} {
		root := strings.TrimSpace(os.Getenv(key))
		if root != "" && strings.HasPrefix(slashed, filepath.ToSlash(root)) {
			return true
		}
	}
	return false
}

// stableBrewEntry trades a versioned Cellar path for the opt symlink Homebrew
// repoints on upgrade, since this one is baked. See docs/aterm-bundles.md.
func stableBrewEntry(entry string) string {
	const cellar = "/Cellar/"
	index := strings.Index(entry, cellar)
	if index < 0 {
		return entry
	}
	// <prefix>/Cellar/<formula>/<version>[/<tail>] becomes <prefix>/opt/<formula>[/<tail>].
	parts := strings.SplitN(entry[index+len(cellar):], string(filepath.Separator), 3)
	if len(parts) < 2 || parts[0] == "" {
		return entry
	}
	stable := filepath.Join(entry[:index], "opt", parts[0])
	if len(parts) == 3 {
		stable = filepath.Join(stable, parts[2])
	}
	// An unlinked formula is reachable only through the Cellar, so a missing
	// opt path means the version pin is the only way there.
	if info, err := os.Stat(stable); err != nil || !info.IsDir() {
		return entry
	}
	return stable
}

func resolveIcon(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", nil
	}
	absolute, err := filepath.Abs(value)
	if err != nil {
		return "", fmt.Errorf("resolve the icon: %w", err)
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return "", fmt.Errorf("inspect the icon %q: %w", absolute, err)
	}
	if info.IsDir() {
		return "", fmt.Errorf("icon %q is a directory", absolute)
	}
	return absolute, nil
}

// staleBundles names a bundle this command wrote that this run does not. It
// deletes nothing, because removing an app is the caller's call.
func staleBundles(output string, keep map[string]bool) []string {
	entries, err := os.ReadDir(output)
	if err != nil {
		return nil
	}
	stale := make([]string, 0)
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".app") {
			continue
		}
		path := filepath.Join(output, entry.Name())
		if _, ours := generatedRole(path); !ours {
			continue
		}
		if keep[path] {
			continue
		}
		stale = append(stale, path)
	}
	if len(stale) == 0 {
		return nil
	}
	return stale
}

// generatedRole identifies our own bundle by what is inside it rather than by
// its name, so renaming the scheme does not orphan what the last run wrote.
func generatedRole(root string) (string, bool) {
	entries, err := os.ReadDir(filepath.Join(root, "Contents", "MacOS"))
	if err != nil {
		return "", false
	}
	marked := false
	for _, entry := range entries {
		// The terminal beside the launcher is a symlink to a binary the size of
		// an application, and only the launcher ever carries the marker.
		if !entry.Type().IsRegular() {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(root, "Contents", "MacOS", entry.Name()))
		if err == nil && strings.Contains(string(raw), bundleMarker) {
			marked = true
			break
		}
	}
	if !marked {
		return "", false
	}
	raw, err := os.ReadFile(filepath.Join(root, "Contents", "Info.plist"))
	if err != nil {
		return "", true
	}
	return plistString(string(raw), "ATermRole"), true
}

// plistString reads one <key>/<string> pair. The plist is ours and one level
// deep, so this stays a read rather than a dependency.
func plistString(document, key string) string {
	marker := "<key>" + key + "</key>"
	index := strings.Index(document, marker)
	if index < 0 {
		return ""
	}
	rest := document[index+len(marker):]
	open := strings.Index(rest, "<string>")
	if open < 0 {
		return ""
	}
	rest = rest[open+len("<string>"):]
	close := strings.Index(rest, "</string>")
	if close < 0 {
		return ""
	}
	return rest[:close]
}

func writeBundle(item bundleItem, icon, tag string) error {
	if err := os.RemoveAll(item.Path); err != nil {
		return fmt.Errorf("clear %q: %w", item.Path, err)
	}
	contents := filepath.Join(item.Path, "Contents")
	executable := filepath.Join(contents, "MacOS", item.Executable)
	if err := os.MkdirAll(filepath.Dir(executable), bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", filepath.Dir(executable), err)
	}
	if err := os.WriteFile(executable, []byte(item.Launcher), bundleExecMode); err != nil {
		return fmt.Errorf("write %q: %w", executable, err)
	}
	plist := filepath.Join(contents, "Info.plist")
	if err := os.WriteFile(plist, []byte(item.Plist), bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", plist, err)
	}
	pkgInfo := filepath.Join(contents, "PkgInfo")
	if err := os.WriteFile(pkgInfo, []byte("APPL????"), bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", pkgInfo, err)
	}
	if item.Terminal != "" {
		terminal := filepath.Join(contents, "MacOS", bundleTerminalName)
		if err := os.Symlink(item.Terminal, terminal); err != nil {
			return fmt.Errorf("link the terminal into %q: %w", terminal, err)
		}
	}
	destination := filepath.Join(contents, "Resources", bundleIconName+".icns")
	switch art := roleIcon(item.Role); {
	case icon != "":
		if err := copyIcon(icon, destination); err != nil {
			return err
		}
	case art != nil:
		if err := writeIconBytes(art, destination); err != nil {
			return err
		}
	}
	// Last: the bundle is complete without it, so a tag is never half a write.
	return tagBundle(item.Path, tag)
}

// replaceable refuses to overwrite anything this command did not write, so a
// mistyped output directory cannot delete an app that happens to share a name.
func replaceable(root string) error {
	if _, err := os.Stat(root); os.IsNotExist(err) {
		return nil
	}
	if _, ours := generatedRole(root); ours {
		return nil
	}
	return fmt.Errorf("%q exists and was not written by `aterm bundles`, so it stays untouched", root)
}

func copyIcon(source, destination string) error {
	raw, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("read the icon %q: %w", source, err)
	}
	return writeIconBytes(raw, destination)
}

func writeIconBytes(raw []byte, destination string) error {
	if err := os.MkdirAll(filepath.Dir(destination), bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", filepath.Dir(destination), err)
	}
	if err := os.WriteFile(destination, raw, bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", destination, err)
	}
	return nil
}

func announceBundles(writer io.Writer, plan bundlePlan) error {
	for _, item := range plan.Items {
		if _, err := fmt.Fprintf(writer, "%s\n", item.Path); err != nil {
			return err
		}
	}
	for _, path := range plan.Stale {
		if _, err := fmt.Fprintf(writer, "stale, this run does not write it: %s\n", path); err != nil {
			return err
		}
	}
	return warnStaleLauncher(writer, plan)
}

func warnStaleLauncher(writer io.Writer, plan bundlePlan) error {
	if !plan.staleLauncher() {
		return nil
	}
	_, err := fmt.Fprintf(writer,
		"warning: these bundles call %s (%s), not this %s build, so they carry only what that build does\n",
		plan.Launcher, plan.LauncherBuild, plan.Build)
	return err
}
